version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: POSTGRES
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
